/**
 * The desktop supervisor row: orchestrates the DSH child process from inside
 * the desktop tree.
 *
 * Responsibilities (P0):
 *   - ensure the desktop runtime dirs under $DSH_HOME/desktop
 *   - start the bridge WS server on a random 127.0.0.1 port
 *   - generate a fresh token and the bridge.yml overlay (env-resolved, so no
 *     secret is baked into the file)
 *   - spawn the DSH CLI as `ELECTRON_RUN_AS_NODE` (reuses the app's own
 *     executable as a Node runtime — no system Node needed)
 *   - wait for the bridge hello (45s), then emit 'desktop/bridge-ready' with
 *     the real web port the child reported (--port 0, OS-assigned)
 *   - respawn the child after a crash (new token, new bridge.yml, new URL)
 *   - tear everything down on dispose (HMR reload / app quit)
 *
 * The bridge RPC surface (dsh.ping/health/restart, desktop.call) and the
 * capability gate land in P1; the wire shape is already in protocol.js.
 *
 * @module dsh-desktop-core/supervisor
 */

import { spawn, exec } from 'node:child_process'
import { existsSync, mkdirSync, renameSync, rmSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { randomBytes, timingSafeEqual } from 'node:crypto'
import { join } from 'node:path'
import { Service } from '@deepseek-ai/cordis'
import z from '@deepseek-ai/schemastery'
import { resolveDshHome } from '@deepseek-ai/dsh-home-paths'
import { createBridgeServer, sendJson } from './ws-server.js'
import { BRIDGE_PATH, HANDSHAKE_NS, HELLO, MAIN_API, PROTOCOL_VERSION, checkFrame, serverResponse } from './protocol.js'

export const name = 'desktop-supervisor'

const KILL_GRACE_MS = 3000

/** Append a line to the app log (best effort, mirrors the old shell). */
function appendLog(file, line) {
  if (!file) return
  try { writeFileSync(file, `[${new Date().toISOString()}] ${line}\n`, { flag: 'a' }) } catch {}
}

/**
 * Resolve the DSH CLI entry. Three anchors, in order:
 *   1. the desktop profile's own node_modules (the upgrade channel — a
 *      profile-local `@deepseek-ai/dsh` wins, which is how `dsh plugin
 *      --profile desktop update` upgrades the runtime independently of the app)
 *   2. the shared flat fallback $DSH_HOME/profiles/node_modules (healed links)
 *   3. the app's dependency closure (dev checkout / bundled fallback)
 * @param dshHome - the harness home.
 * @param binOverride - config override (absolute path).
 */
function resolveDshBin(dshHome, binOverride) {
  if (binOverride) {
    if (existsSync(binOverride)) return binOverride
    throw new Error(`desktop-supervisor: configured spawnBin does not exist: ${binOverride}`)
  }
  const candidates = [
    join(dshHome, 'profiles', 'desktop', 'node_modules', '@deepseek-ai', 'dsh', 'lib', 'bin.js'),
    join(dshHome, 'profiles', 'node_modules', '@deepseek-ai', 'dsh', 'lib', 'bin.js'),
  ]
  for (const candidate of candidates) {
    if (existsSync(candidate)) return candidate
  }
  try {
    return createRequire(import.meta.url).resolve('@deepseek-ai/dsh/lib/bin.js')
  } catch (error) {
    throw new Error(`desktop-supervisor: cannot resolve the dsh CLI (tried profile, shared fallback, app closure): ${error.message}`)
  }
}

/** The bridge.yml overlay written fresh on every spawn cycle. */
function renderBridgeYml() {
  return [
    '# Generated by dsh-desktop-app — overwritten on every launch; do not edit.',
    '# The token travels through the child environment; the file only names it.',
    '- insert:',
    '    - id: desktop-bridge',
    "      name: 'dsh-desktop-bridge'",
    '      config:',
    '        url: !!js process.env.DSH_DESKTOP_BRIDGE_URL',
    '        token: !!js process.env.DSH_DESKTOP_TOKEN',
    '',
  ].join('\n')
}

function safeEqual(a, b) {
  const left = Buffer.from(String(a ?? ''))
  const right = Buffer.from(String(b ?? ''))
  return left.length === right.length && timingSafeEqual(left, right)
}

export default class SupervisorService extends Service {
  /** Service-row config, validated by the Loader at activation. */
  static Config = z.object({
    /** The DSH child argv, starting from the surface command ('web', ...). */
    spawnArgs: z.array(String).default(['web', '--port', '0']),
    /** Override for the DSH CLI entry to spawn (defaults to three-anchor resolution). */
    spawnBin: z.string().default(''),
    /** Grace before we stop waiting for the hello handshake. */
    helloTimeoutMs: z.number().min(1000).default(45000),
    /** Delay before respawning a crashed child. */
    respawnDelayMs: z.number().min(0).default(3000),
    /** Absolute log path for child output and supervisor diagnostics. */
    logPath: z.string().default(''),
    /** The DSH home; defaults to resolveDshHome(). */
    dshHome: z.string().default(''),
  })

  constructor(ctx, config) {
    super(ctx, 'desktopSupervisor')
    this.config = config
    this.logger = ctx.logger('desktop-supervisor')
    this.dshHome = config.dshHome || resolveDshHome()
    this.logFile = config.logPath || join(this.dshHome, 'desktop', 'app.log')
    this.state = 'starting'
    this.webPort = null
    this.protocolVersion = null
    this.child = null
    this.bridge = null
    this.token = null
    this.disposed = false
    this.respawnTimer = null
    this.helloTimer = null
    this.helloResolver = null
    // Service has no dispose hook; ctx effects are how Cordis rows clean up
    // (same pattern as the window row). Deterministic teardown on HMR reload
    // and on app quit.
    ctx.effect(() => () => this._dispose())
  }

  log(line) {
    this.logger.info(line)
    appendLog(this.logFile, `supervisor: ${line}`)
  }

  async [Service.init]() {
    // Fire-and-forget on purpose: init must settle immediately so the Loader
    // never awaits a long-lived spawn cycle. Disposal owns the teardown.
    this._spawnCycle().catch((error) => {
      if (this.disposed) return
      this.log(`spawn cycle failed: ${error.message}`)
      this.state = 'degraded'
    })
  }

  _emitReady() {
    this.state = 'ready'
    this.log(`bridge ready: web http://127.0.0.1:${this.webPort} protocol v${this.protocolVersion}`)
    this.ctx.emit('desktop/bridge-ready', {
      port: this.webPort,
      protocolVersion: this.protocolVersion,
    })
  }

  async _spawnCycle() {
    if (this.disposed) return
    this.state = 'starting'
    // A respawn cycle must not leak the previous bridge (old token/URL).
    if (this.bridge) {
      try { await this.bridge.close() } catch (error) { this.log(`bridge close: ${error.message}`) }
      this.bridge = null
      this.readySocket = null
    }
    try {
      await this._startBridge()
    } catch (error) {
      this.log(`bridge server failed: ${error.message}`)
      this.state = 'degraded'
      return
    }
    this.token = randomBytes(32).toString('base64url')
    mkdirSync(join(this.dshHome, 'desktop'), { recursive: true })
    const bridgeYmlPath = join(this.dshHome, 'desktop', 'bridge.yml')
    try {
      const tmp = `${bridgeYmlPath}.tmp`
      writeFileSync(tmp, renderBridgeYml())
      renameSync(tmp, bridgeYmlPath)
    } catch (error) {
      this.log(`failed to write ${bridgeYmlPath}: ${error.message}`)
      this.state = 'degraded'
      return
    }
    const bin = resolveDshBin(this.dshHome, this.config.spawnBin)
    // The rc.7 launcher stops option parsing at the first positional token
    // (passThroughOptions), so --patch must sit right after the surface
    // command ('web' / '--profile'), before any inner arg like --port 0.
    const args = [...this.config.spawnArgs]
    const surfaceIndex = args.findIndex((arg) => arg === 'web' || arg === '--profile')
    if (surfaceIndex >= 0) args.splice(surfaceIndex + 1, 0, '--patch', bridgeYmlPath)
    else args.splice(0, 0, '--patch', bridgeYmlPath)
    // The DSH child needs --expose-internals: the loader's internal import
    // (module resolution from the profile dir) and the web tree's HMR row
    // both require it, and unlike the Electron main process, ELECTRON_RUN_AS_NODE
    // accepts the flag. Without it the web tree fails at boot (HMR service).
    const child = spawn(process.execPath, ['--expose-internals', bin, ...args], {
      cwd: this.dshHome,
      env: {
        ...process.env,
        ELECTRON_RUN_AS_NODE: '1',
        DSH_HOME: this.dshHome,
        DSH_DESKTOP_BRIDGE_URL: this.bridge.url,
        DSH_DESKTOP_TOKEN: this.token,
      },
      windowsHide: true,
      stdio: ['ignore', 'pipe', 'pipe'],
    })
    this.child = child
    this.log(`spawned dsh (pid ${child.pid}): --expose-internals ${bin} ${args.join(' ')}`)
    child.stdout?.on('data', (chunk) => appendLog(this.logFile, `dsh: ${String(chunk).trimEnd()}`))
    child.stderr?.on('data', (chunk) => appendLog(this.logFile, `dsh: ${String(chunk).trimEnd()}`))
    child.on('error', (error) => {
      this.log(`dsh child error: ${error.message}`)
      this.state = 'degraded'
    })
    child.on('exit', (code, signal) => {
      this.log(`dsh child exited (code ${String(code)}, signal ${String(signal)})`)
      this.child = null
      if (this.disposed) return
      this.state = 'degraded'
      this.respawnTimer = setTimeout(() => {
        this.respawnTimer = null
        this._spawnCycle()
      }, this.config.respawnDelayMs)
    })

    await this._awaitHello()
  }

  _startBridge() {
    return createBridgeServer({
      path: BRIDGE_PATH,
      log: (line) => this.log(line),
      onFrame: (frame, socket) => this._onFrame(frame, socket),
    }).then((bridge) => {
      this.bridge = bridge
      this.log(`bridge listening at ${bridge.url}`)
    })
  }

  _onFrame(frame, socket) {
    try {
      checkFrame(frame)
    } catch (error) {
      this.log(`bad frame: ${error.message}`)
      return
    }
    if (frame.kind !== 'client-request' || frame.ns !== HANDSHAKE_NS || frame.method !== HELLO) {
      // P1 routes the full RPC surface; P0 only answers the handshake.
      return
    }
    const payload = frame.payload
    if (!safeEqual(payload?.token, this.token)) {
      this.log('bridge: hello rejected (bad token)')
      sendJson(socket, serverResponse(frame.id, false, undefined, 'unauthorized'))
      try { socket.destroy() } catch {}
      return
    }
    const webPort = payload?.webPort
    if (typeof webPort !== 'number' || !Number.isInteger(webPort)) {
      sendJson(socket, serverResponse(frame.id, false, undefined, 'webPort must be an integer'))
      return
    }
    this.webPort = webPort
    this.protocolVersion = Number(payload.protocolVersion ?? 1)
    sendJson(socket, serverResponse(frame.id, true, {
      protocolVersion: PROTOCOL_VERSION,
      api: MAIN_API,
    }))
    this.log(`hello accepted from dsh (web port ${webPort}, child protocol v${this.protocolVersion})`)
    if (this.helloTimer) {
      clearTimeout(this.helloTimer)
      this.helloTimer = null
    }
    this.helloResolver?.()
    this.helloResolver = null
    this._emitReady()
  }

  _awaitHello() {
    return new Promise((resolve) => {
      this.helloResolver = resolve
      this.helloTimer = setTimeout(() => {
        this.helloTimer = null
        this.helloResolver = null
        this.log(`no hello within ${this.config.helloTimeoutMs}ms; keeping the child running and waiting`)
        resolve()
      }, this.config.helloTimeoutMs)
      this.helloTimer.unref?.()
    })
  }

  async _dispose() {
    if (this.disposed) return
    this.disposed = true
    if (this.respawnTimer) {
      clearTimeout(this.respawnTimer)
      this.respawnTimer = null
    }
    if (this.helloTimer) {
      clearTimeout(this.helloTimer)
      this.helloTimer = null
    }
    this.helloResolver?.()
    this.helloResolver = null
    const child = this.child
    this.child = null
    if (child && child.pid) {
      this.log(`stopping dsh (pid ${child.pid})`)
      try { child.kill('SIGTERM') } catch {}
      await new Promise((resolve) => setTimeout(resolve, KILL_GRACE_MS))
      if (child.exitCode === null && child.signalCode === null) {
        await new Promise((resolve) => {
          exec(`taskkill /pid ${child.pid} /T /F`, () => resolve())
        })
      }
    }
    if (this.bridge) {
      try { await this.bridge.close() } catch (error) { this.log(`bridge close: ${error.message}`) }
      this.bridge = null
    }
    try { rmSync(join(this.dshHome, 'desktop', 'bridge.yml'), { force: true }) } catch {}
    this.log('supervisor disposed')
  }
}
